### ISSUE TITLE
Cannot find module 'react-dev-utils/WatchMissingNodeModulesPlugin'

### ISSUE THREAD

**Issue by jarismar** [amazon-connect/amazon-connect-chat-interface#75]
I'm trying to customize the chat widget, going through the docs It asks to run `npm install && npm run dev-build` to setup a local dist folder.
But hen running `npm dev-build` the command fails with this error:

```
$ npm run dev-build

> @amzn/connect-chat-interface@1.0.0 dev-build
> NODE_ENV=development npx webpack --config configuration/webpack.config.dev.js

[webpack-cli] Failed to load '/Users/jsilva3/workspace/amazon-connect-chat-interface/configuration/webpack.config.dev.js' config
[webpack-cli] Error: Cannot find module 'react-dev-utils/WatchMissingNodeModulesPlugin'
Require stack:
- /Users/jsilva3/workspace/amazon-connect-chat-interface/configuration/webpack.config.dev.js
- /Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/webpack-cli/lib/bootstrap.js
- /Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/webpack-cli/bin/cli.js
- /Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/jsilva3/workspace/amazon-connect-chat-interface/configuration/webpack.config.dev.js:9:39)
    at Module._compile (/Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jsilva3/workspace/amazon-connect-chat-interface/configuration/webpack.config.dev.js',
    '/Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/webpack-cli/bin/cli.js',
    '/Users/jsilva3/workspace/amazon-connect-chat-interface/node_modules/webpack/bin/webpack.js'
  ]
}
```

Node version: v16.14.0
Npm version: 8.3.1
OS: MacOS Monterey 12.6

**Comment by spencerlepine** [comment]
Thank you for raising this issue.

Currently working on a fix with PR #77.

For now, you can try updating the `configuration/webpack.config.dev.js` file by removing the following lines:
```diff
- const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin');
 
 module.exports = {
     // ...
     plugins: [
-        // If you require a missing module and then `npm install` it, you still have
-        // to restart the development server for Webpack to discover it. This plugin
-        // makes the discovery automatic so you don't have to restart.
-        // See https://github.com/facebook/create-react-app/issues/186
-        new WatchMissingNodeModulesPlugin(paths.appNodeModules),
     ]
 }
```

**Comment by jarismar** [comment]
Thank you, it worked after commenting out those lines.
